name: tekartik_io_tools
version: 0.0.1
description: A minimal command-line application.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: any
  path: any
  logging: any
  tekartik_core:
    git: git://github.com/alextekartik/tekartik_core.dart.git
dev_dependencies:
  unittest: any
dependency_overrides:
#  tekartik_core:
#    path: ../tekartik_core.dart
  
