name: tekartik_io_tools
version: 0.4.0
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: any
  logging: any
  path: any
  pool: any
  yaml: any
  tekartik_core:
    git: git://github.com/alextekartik/tekartik_core.dart
dev_dependencies:
  dev_test:
    git: git://github.com/alextekartik/dev_test.dart
  test: any
executables:
  rscpull:
  rscstatus:
  rpubtest:
  rpubupgrade:
dependency_overrides:
