name: tekartik_io_tools
version: 0.8.2
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: any
  logging: any
  path: any
  pool: any
  yaml: any
  process_run: any
  tekartik_core:
    git: git://github.com/alextekartik/tekartik_core.dart
  tekartik_pub:
    git: git://github.com/tekartik/pub.dart
dev_dependencies:
  dev_test: any
  test: any
executables:
dependency_overrides:
#  tekartik_pub:
#    path: /media/ssd/devx/git/github.com/tekartik/tekartik_pub.dart
