name: tekartik_io_tools
version: 0.7.1
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: any
  logging: any
  path: any
  pool: any
  yaml: any
  tekartik_core:
    git: git://github.com/alextekartik/tekartik_core.dart
  tekartik_pub:
    git: git://github.com/tekartik/tekartik_pub.dart
dev_dependencies:
  dev_test: any
  test: any
executables:
  rscpull:
  rscstatus:
  rpubtest:
  rpubupgrade:
dependency_overrides:
  tekartik_pub:
    path: /media/ssd/devx/git/github.com/tekartik/tekartik_pub.dart
