name: tekartik_io_tools
version: 0.0.5
description: A minimal command-line application.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: any
  logging: any
  path: any
  tekartik_core:
    git: git://github.com/alextekartik/tekartik_core.dart
dev_dependencies:
  tekartik_test:
    git: git://github.com/alextekartik/tekartik_test.dart
  test: any
executables:
   rgitpull:
   rscstatus:
dependency_overrides: null
